### ISSUE TITLE
.net 3.5 compability

### ISSUE THREAD

**Issue by thereis** [xiaoyuvax/NHttp.Core#1]
Hello, I was wondering if this version has support for .net framework 3.5. I've came here for the original NHttp repository which I was missing the support for TLS.

Is the TLS/HTTPS support only available for .net standard?

**Comment by xiaoyuvax** [comment]
directly, no. this project is targeting .net core 2.0,which must work with .net 4.6.1 or above.
if not wrong ,i do rememebr there's a problem with X95Certificate2 class in earlier .net framework version, while the core framework was rewritten by microsoft with this problem mitigated somehow.
you may try to copy the code into a 3.5 project and try it out, and luck would be if it works for you, and don't forget to mention your success here.
otherwise ,why not upgrade?

**Comment by thereis** [comment]
Thanks for the fast answer! The reason that I'm not upgrading to a new version of .net, it is because I'm running NHttp on a Unity game server and it was built on the .net framework 3.5.

Plugin developers for this game are limited to build their plugins and stuffs in this old version and I'm implementing a http web service to communicate remotely with the game, because there is no support for grpc server or other comunication protocol for my situation.

I'll clone the repository later and then try to compile by myself to the .net 3.5.

Thanks!
